services: mysql
  - mysql
  - memcached
before_install:
  - mysql -e "CREATE DATABASE Sandbox;"
  - mysql -e "CREATE USER 'mytool'@'localhost' IDENTIFIED BY 'aComplex1';"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'mytool'@'localhost' WITH GRANT OPTION;"
  - dev/scripts/database/schema.reset.sh
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y make autoconf automake libtool gdb valgrind valgrind-dbg cmake pkg-config sysstat inotify-tools
  - sudo apt-get install -y libc6-dev libc++-dev libbsd-dev libncurses5-dev libmpfr4 libmpfr-dev libsubunit-dev libsubunit0 
language: c
compiler: gcc
script: make all
sudo: required
dist: trusty
