services: mysql
  - mysql
  - memcached
before_install:
  - mysql -e "CREATE DATABASE Sandbox;"
  - mysql -e "CREATE USER 'mytool'@'localhost' IDENTIFIED BY 'aComplex1';
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'mytool'@'localhost' WITH GRANT OPTION;"
  - dev/scripts/database/schema.reset.sh
install: make get-deps
language: c
compiler: gcc
script: make all
