os: linux
language: c++
dist: trusty
group: stable
compiler: gcc
services: 
  - mysql
  - memcached
addons:
  apt:
    packages:
    - libbsd-dev
    - gdb
    - make 
    - cmake
    - autoconf 
    - automake 
    - libtool
    - valgrind 
    - pkg-config
    - valgrind-dbg
    - libsubunit-dev
    - build-essential
    - sysstat
    - inotify-tools
    - libc6-dev
    - ibc++-dev
    - libncurses5-dev 
    - libmpfr4 
    - libmpfr-dev
    - gcc
    - g++
    - gcc-multilib
    - flex
    - bison
    - libpython2.7
    - patch
    - libarchive13
    - libsubunit-dev
    - libsubunit0
    - git
    - git-man
    - rsync
    - wget
    - curl
    - rsync
    - gnupg
    - mlocate
    - sysstat
    - lsof
    - pciutils
    - usbutils
before_script:
  - export HOSTNAME=`hostname`
  - mysql -e "CREATE DATABASE Sandbox;"
  - mysql -e "CREATE USER 'mytool'@'localhost' IDENTIFIED BY 'aComplex1';"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'mytool'@'localhost' WITH GRANT OPTION;"
  - dev/scripts/database/schema.reset.sh
script: 
  - export HOSTNAME=`hostname`
  - git remote add upstream https://github.com/lavabit/magma.git
  - git fetch upstream
  - git merge upstream/develop
  - dev/scripts/builders/build.lib.sh extract
  - dev/scripts/builders/build.lib.sh prep
  - dev/scripts/builders/build.lib.sh follow | grep -E "^making" &
  - (for ((i = 0; i < 60; ++i)); do date ; sleep 60; done) & LOOP_PID=$!
  - dev/scripts/builders/build.lib.sh build
  - dev/scripts/builders/build.lib.sh combine
  - killall tail && kill $LOOP_PID
  - sed -i -e "/magma.iface.database.socket_path/d" sandbox/etc/magma.sandbox.config
  - sed -i -e "/magma.iface.database.host/d" sandbox/etc/magma.sandbox.config
  - printf "magma.iface.database.host = 127.0.0.1\n" >> sandbox/etc/magma.sandbox.config
  - printf "magma.system.domain = travis.local\n" >> sandbox/etc/magma.sandbox.config
  - printf "magma.secure.memory.enable = false\n" >> sandbox/etc/magma.sandbox.config
  - chmod 700 sandbox/etc/tls.localhost.localdomain.pem
  - chmod 700 sandbox/etc/dkim.localhost.localdomain.pem
  - chmod 700 sandbox/etc/dime.localhost.localdomain.key
  - chmod 700 sandbox/etc/dime.localhost.localdomain.signet
  - make all
  - make check
  
