os: linux
language: c
compiler: gcc
sudo: required
notifications:
  email:
    on_success: never
    on_failure: never
cache:
  - directories:
    - $HOME/packages/
matrix:
  include:
  - stage: cache
    dist: trusty
    script: true
  - stage: cache
    dist: xenial
    script: true
  - stage: run
    dist: trusty
    before_script:
      -  export FLAGS='-DMAGMA_PEDANTIC -O0' ; export TARGET=all ; export COMPILER=gcc
  - stage: run
    dist: trusty
    before_script:
      -  export FLAGS='-UMAGMA_PEDANTIC -O0' ; export TARGET=all ; export COMPILER=gcc
  - stage: run
    dist: xenial
    before_script:
      - export FLAGS='-DMAGMA_PEDANTIC -O0' ; export TARGET=all ; export COMPILER=gcc
      - sudo systemctl start mysql && sudo systemctl start postfix && sudo systemctl start memcached
  - stage: run
    dist: xenial
    before_script:
      - export FLAGS='-UMAGMA_PEDANTIC -O0' ; export TARGET=all ; export COMPILER=gcc
      - sudo systemctl start mysql && sudo systemctl start postfix && sudo systemctl start memcached
before_install:
  - sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
  - curl -sSL "https://build.travis-ci.org/files/gpg/llvm-toolchain-`lsb_release -c -s`-6.0.asc" | sudo -E apt-key add -
  - echo "deb https://apt.llvm.org/`lsb_release -c -s`/ llvm-toolchain-`lsb_release -c -s`-6.0 main" | sudo tee -a ${TRAVIS_ROOT}/etc/apt/sources.list >/dev/null
  - if [ -d $HOME/packages ]; then find $HOME/packages -maxdepth 1 -type f -name "*.deb" -exec sudo cp {} /var/cache/apt/archives/ \; ; fi
  - if [ ! -d $HOME/packages ]; then mkdir $HOME/packages; fi
install:
  - sudo apt-get update
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends install autoconf automake bison build-essential cmake curl flex gdb git gnupg ibc++-dev inotify-tools libarchive13 libbsd-dev libc6-dev libmpfr4 libmpfr-dev libncurses5-dev libpython2.7 libsubunit0 libsubunit-dev libtool make patch pciutils pkg-config postfix sysstat usbutils valgrind valgrind-dbg gcc-4.8 g++-4.8 gcc-4.8-locales gcc-4.8-multilib g++-4.8-multilib libstdc++-4.8-dev gcc-4.9 g++-4.9 gcc-4.9-locales gcc-4.9-multilib g++-4.9-multilib libstdc++-4.9-dev gcc-5 g++-5 gcc-5-locales gcc-5-multilib g++-5-multilib libstdc++-5-dev gcc-6 g++-6 gcc-6-locales gcc-6-multilib g++-6-multilib libstdc++-6-dev gcc-7 g++-7 gcc-7-locales gcc-7-multilib g++-7-multilib libstdc++-7-dev gcc-8 g++-8 gcc-8-locales gcc-8-multilib g++-8-multilib libstdc++-8-dev clang-6.0 llvm-6.0-dev
  - if [ "`lsb_release -c -s`" == "xenial" ]; then sudo -E apt-get -yq --no-install-suggests --no-install-recommends install memcached mysql-client mysql-server; fi
  - find /var/cache/apt/archives/ -maxdepth 1 -type f -name "*.deb" -exec cp {} $HOME/packages/ \;
script: 
  - export HOSTNAME=`hostname`
  - mysql -e "CREATE DATABASE Sandbox;"
  - mysql -e "CREATE USER 'mytool'@'localhost' IDENTIFIED BY 'aComplex1';"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'mytool'@'localhost' WITH GRANT OPTION;"
  - cd $HOME && curl --location --output util-linux-2.25.2.tar.gz https://www.kernel.org/pub/linux/utils/util-linux/v2.25/util-linux-2.25.2.tar.gz
  - tar xzf util-linux-2.25.2.tar.gz && cd util-linux-2.25.2
  - ./configure ADJTIME_PATH=/var/lib/hwclock/adjtime --disable-chfn-chsh --disable-login --disable-nologin --disable-su --disable-setpriv --disable-runuser --disable-pylibmount --disable-static --without-python --without-systemd --without-systemdsystemunitdir --without-ncurses
  - make prlimit && install --verbose --directory $HOME/bin/ && install --verbose --mode=755 prlimit $HOME/bin/prlimit && cd $TRAVIS_BUILD_DIR
  - export HASH=`git show  --quiet | grep commit | awk -F' ' '{print $2}'`
  - git remote add upstream https://github.com/lavabit/magma.git
  - git fetch upstream
  - git reset --hard upstream/develop
  - git checkout $HASH -- .travis.yml
  - sudo -E $HOME/bin/prlimit --pid "$$" --stack=unlimited:unlimited;
  - sudo -E $HOME/bin/prlimit --pid "$$" --memlock=unlimited:unlimited;
  - (for ((i = 0; i < 60; ++i)); do sleep 60 ; printf "%s (%s )\n" "`date`" "`uptime`" ; done) & LOOP_PID=$! ; disown 
  - dev/scripts/database/schema.reset.sh
  - dev/scripts/builders/build.lib.sh extract
  - dev/scripts/builders/build.lib.sh prep
  - dev/scripts/builders/build.lib.sh build
  - (dev/scripts/freshen/freshen.clamav.sh &> /dev/null) &
  - dev/scripts/builders/build.lib.sh combine
  - dev/scripts/builders/build.lib.sh load
  - kill $LOOP_PID
  - sed -i -e "/magma.iface.database.socket_path/d" sandbox/etc/magma.sandbox.config
  - sed -i -e "/magma.iface.database.host/d" sandbox/etc/magma.sandbox.config
  - sed -i -e "/magma.library.file/d" sandbox/etc/magma.sandbox.config
  - printf "magma.library.file = $TRAVIS_BUILD_DIR/magmad.so\n" >> sandbox/etc/magma.sandbox.config
  - printf "magma.iface.database.host = 127.0.0.1\n" >> sandbox/etc/magma.sandbox.config
  - printf "magma.secure.memory.enable = true\n" >> sandbox/etc/magma.sandbox.config
  - chmod 700 sandbox/etc/tls.localhost.localdomain.pem
  - chmod 700 sandbox/etc/dkim.localhost.localdomain.pem
  - chmod 700 sandbox/etc/dime.localhost.localdomain.key
  - chmod 700 sandbox/etc/dime.localhost.localdomain.signet
  - CC="$COMPILER" CFLAGS="$FLAGS" make --keep-going --jobs=4 $TARGET && dev/scripts/launch/check.run.sh
 
