os: linux
language: c
dist: trusty
group: stable
compiler: gcc
sudo: required
services: mysql
install:
  - sudo apt-get -qq update
  - sudo apt-get --yes install libbsd-dev
  - sudo service memcached start
before_script:
  - mysql -e "CREATE DATABASE Sandbox;"
  - mysql -e "CREATE USER 'mytool'@'localhost' IDENTIFIED BY 'aComplex1';"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'mytool'@'localhost' WITH GRANT OPTION;"
  - dev/scripts/database/schema.reset.sh
script: make all
