os: linux
language: c++
dist: trusty
group: stable
compiler: gcc
services: 
  - mysql
  - memcached
addons:
  apt:
    packages:
    - libbsd-dev
    - gdb
    - make 
    - cmake
    - autoconf 
    - automake 
    - libtool
    - valgrind 
    - pkg-config
    - valgrind-dbg  
    - libsubunit-dev
    - build-essential
    - sysstat
    - inotify-tools
    - libc6-dev
    - ibc++-dev
    - libncurses5-dev 
    - libmpfr4 
    - libmpfr-dev
before_script:
  - mysql -e "CREATE DATABASE Sandbox;"
  - mysql -e "CREATE USER 'mytool'@'localhost' IDENTIFIED BY 'aComplex1';"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'mytool'@'localhost' WITH GRANT OPTION;"
  - dev/scripts/database/schema.reset.sh
script: 
  - dev/scripts/builders/build.lib.sh extract
  - dev/scripts/builders/build.lib.sh prep
  - dev/scripts/builders/build.lib.sh follow | grep -E "^making" &
  - dev/scripts/builders/build.lib.sh build
  - dev/scripts/builders/build.lib.sh combine
  - make all
  
