services: mysql
  - mysql
  - memcached
before_install:
  - mysql -e 'CREATE DATABASE magma;'
  - dev/scripts/database/schema.reset.sh travis "" magma
install: make get-deps
language: c
compiler: gcc
script: make all
