os: linux
language: c++
dist: trusty
group: stable
compiler: gcc
services: 
  - mysql
  - memcached
addons:
  apt:
    packages:
    - libbsd-dev
    - gdb
    - make 
    - cmake
    - autoconf 
    - automake 
    - libtool
    - valgrind 
    - pkg-config
    - valgrind-dbg
    - libsubunit-dev
    - build-essential
    - sysstat
    - inotify-tools
    - libc6-dev
    - ibc++-dev
    - libncurses5-dev 
    - libmpfr4 
    - libmpfr-dev
    - gcc
    - g++
    - gcc-multilib
    - flex
    - bison
    - libpython2.7
    - patch
    - libarchive13
    - libsubunit-dev
    - libsubunit0
    - git
    - git-man
    - liberror-perl
    - rsync
    - wget
    - liberror-perl
    - wget
    - curl
    - rsync
    - gnupg
    - mlocate
    - sysstat
    - lsof
    - pciutils
    - usbutils
    - mysql-client
    - mysql-server
    - perl
    - libdbi-perl
    - mysql-common
    - libdbd-mysql-perl
before_script:
  - mysql -e "CREATE DATABASE Sandbox;"
  - mysql -e "CREATE USER 'mytool'@'localhost' IDENTIFIED BY 'aComplex1';"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'mytool'@'localhost' WITH GRANT OPTION;"
  - dev/scripts/database/schema.reset.sh
script: 
  - git remote add upstream https://github.com/lavabit/magma.git
  - git fetch upstream
  - git merge upstream/develop
  - dev/scripts/builders/build.lib.sh extract
  - dev/scripts/builders/build.lib.sh prep
  - dev/scripts/builders/build.lib.sh follow | grep -E "^making" &
  - for ((i = 0; i < 60; ++i)); do date ; sleep 60; done &
  - dev/scripts/builders/build.lib.sh build
  - dev/scripts/builders/build.lib.sh combine
  - make all
  - make check
  
